### ISSUE TITLE
ActionSheetStringPicker not working on iPad (only iPhone)

### ISSUE THREAD

**Issue by danielmapar** [skywinder/ActionSheetPicker-3.0#156] opened 2015-03-26 21:03 UTC
When I call ActionSheetStringPicker on the iPad the screen fades, but the selection won't show up. It just works on my iPhone.

Here follows the code:

``` objective-c
- (BOOL)textFieldShouldBeginEditing:(UITextField *)textField
{
    if(textField.tag == 200){
        NSMutableArray *groups = [[NSMutableArray alloc] init];

        for (Group *group in [Group sharedUserGroups]) {
            [groups addObject:group.name];
        }

        [ActionSheetStringPicker showPickerWithTitle:@"Select a Group"
                                                rows:groups
                                    initialSelection:0
                                           doneBlock:^(ActionSheetStringPicker *picker, NSInteger selectedIndex, id selectedValue) {
                                                textField.text = selectedValue;
                                                }
                                         cancelBlock:^(ActionSheetStringPicker *picker) {
                                             NSLog(@"Block Picker Canceled");
                                         }
                                              origin:self.view];
```

![screen shot 2015-03-26 at 4 59 17 pm](https://cloud.githubusercontent.com/assets/4336805/6856925/921976ea-d3d9-11e4-8118-daded34f159a.png)
![screen shot 2015-03-26 at 4 59 55 pm](https://cloud.githubusercontent.com/assets/4336805/6856924/9218de60-d3d9-11e4-8004-29a32f0bbeb8.png)

**Comment by skywinder** [comment] 2015-03-26 21:50
Hi! It seems pretty similar to #131 PR! Can you check, is this fix works for you?

**Comment by danielmapar** [comment] 2015-03-26 22:07
I tried to apply the fix to presentActionSheet, but I am not sure how to do it:
```objective-c
- (void)presentActionSheet:(SWActionSheet *)actionSheet
{
    NSParameterAssert(actionSheet != NULL);
    if ( self.barButtonItem )
        [actionSheet showFromBarButtonItem:_containerView.bounds animated:YES];
    else
        [actionSheet showInContainerView];

```

Could you provide me with some code?

**Comment by skywinder** [comment] 2015-03-26 22:31
just find string in `AbstractActionSheetPicker.m`:

    [popover presentPopoverFromBarButtonItem:_barButtonItem permittedArrowDirections:UIPopoverArrowDirectionAny
    animated:YES];

and replace it to 

    [popover presentPopoverFromRect:CGRectMake(_containerView.frame.size.width / 2.f, 0.f, 0, 0) inView:_containerView permittedArrowDirections:UIPopoverArrowDirectionAny animated:YES];

and check, is it works?

**Comment by danielmapar** [comment] 2015-03-26 22:36
Does not work.

**Comment by skywinder** [comment] 2015-03-26 22:44
ok. 
So, lets investigate the problem. What about `origin`? Are you sure, that self.view is not overlapping by another views?

**Comment by danielmapar** [comment] 2015-03-26 22:51
I don't think so. Otherwise, the iPhone version would not be working as well.

**Comment by danielmapar** [comment] 2015-03-31 23:06
Any idea?

**Comment by skywinder** [comment] 2015-04-01 06:33
It's very hard to debug without source code. 
But most probably the problem in `origin` parameter. Try to change it from `self.view` to textField with tag 200.

**Comment by benjamingroeber** [comment] 2015-04-02 16:12
Tanks for pointing out the `origin` parameter. Indeed I was stuck for a few hours figuring out why the overlay was stuck to the upper bar. 
![tios_simulator_screen_shot_02042015_180602](https://cloud.githubusercontent.com/assets/6244046/6968022/af081b82-d963-11e4-9979-bcd945b20a69.png)
Setting it to the individual view did the trick.

Thanks and keep up the good work!
Cheers, 
Ben

**Comment by skywinder** [comment] 2015-04-02 16:25
@benjamingroeber great, but, as I can see on screenshot - the issue is not completely resolved.  Please, try to do what I described above https://github.com/skywinder/ActionSheetPicker-3.0/issues/156#issuecomment-86740835 is it helps?

@danielmapar  how it's going? Did you try to change origin?

**Comment by benjamingroeber** [comment] 2015-04-03 07:51
Sorry for not being clear, this was the before state, after state looks like this: 
![tios_simulator_screen_shot_02042015_180641](https://cloud.githubusercontent.com/assets/6244046/6979647/ea03bdc6-d9e6-11e4-93a2-536457d82399.png)

**Comment by skywinder** [comment] 2015-04-03 07:59
@benjamingroeber 

>Also I already included your fix

Are you mean you are replace the strings, that I described? Is it helps?
It's related with PR #131 . I can't reproduce this problem and need prove - is this PR useful or not. Thay's why I'm asking is it help or not.

**Comment by benjamingroeber** [comment] 2015-04-03 08:13
I'm sorry, I tested both versions right now, but in this case it didn't really change the outcome. 
I assume my Problem was definitely just the wrong `origin`.

**Comment by skywinder** [comment] 2015-04-03 11:11
@benjamingroeber ok, thanks for clarify.

@danielmapar Waiting for your feedback.

**Comment by danielmapar** [comment] 2015-04-16 05:53
Sorry for the delay skywinder. Changing from self.view to textField solved the problem completely.

**Comment by danielmapar** [comment] 2015-04-16 05:54
![screen shot 2015-04-16 at 1 54 31 am](https://cloud.githubusercontent.com/assets/4336805/7174843/895520f6-e3db-11e4-9c0d-5e9f1d03add5.png)

**Comment by skywinder** [comment] 2015-04-16 07:24
@danielmapar :+1:

**Comment by VinayagamD** [comment] 2015-06-25 12:05
This time it is on button press not for text field

**Comment by giantslogik** [comment] 2015-07-01 11:01
Ran into the same issue. The #187 fix did not work.
Complete fix for me. (same position as the #187 fix)
  NSParameterAssert(popover != NULL);
    if (self.barButtonItem) {
        if (UI_USER_INTERFACE_IDIOM() == UIUserInterfaceIdiomPhone)
        {
            [popover presentPopoverFromBarButtonItem:_barButtonItem permittedArrowDirections:UIPopoverArrowDirectionAny
                                        animated:YES];
        }else{
            [popover presentPopoverFromRect:CGRectMake(_containerView.frame.size.width / 2.f, _containerView.frame.size.height, 0, 0) inView:_containerView permittedArrowDirections:UIPopoverArrowDirectionAny animated:YES];
        }
        return;
    }
    else if ((self.containerView)) {
        if (UI_USER_INTERFACE_IDIOM() == UIUserInterfaceIdiomPhone)
        {
        dispatch_async(dispatch_get_main_queue(), ^{
            [popover presentPopoverFromRect:_containerView.bounds inView:_containerView
                   permittedArrowDirections:UIPopoverArrowDirectionAny animated:YES];

        });
        }else{
            [popover presentPopoverFromRect:CGRectMake(_containerView.frame.size.width / 2.f, _containerView.frame.size.height, 0, 0)inView:_containerView
                   permittedArrowDirections:UIPopoverArrowDirectionAny animated:YES];
        }
        return;
    }

**Comment by giantslogik** [comment] 2015-07-01 11:06
Evidently _containerView.bounds is broken on ipad ios8.3

**Comment by fitch** [comment] 2015-09-30 08:56
On iPad iOS 8.4.1 I'm facing the same issue with self.view (when the view frame is full screen).

**Comment by skywinder** [comment] 2015-09-30 09:21
@giantslogik @fitch  Ok, I reopen this issue, since it appears in your cases

**Comment by giantslogik** [comment] 2015-09-30 09:42
Let me check if my fix (above) works on 8.4.1 and 9. @skywinder

**Comment by fitch** [comment] 2015-09-30 10:13
(Problem also with `ActionSheetDatePicker`)

**Comment by AruLNadhaN** [comment] 2015-09-30 11:45
i'm also facing this Issue in iPad.

This is how my code looks         

let StringPicker = ActionSheetStringPicker(title: "Hey", rows: ["Hello","Hello","Hello","Hello","Hello","Hello","Hello"], initialSelection: 0, target: self, successAction: Selector("measurementWasSelected:smallUnit:element:"), cancelAction: Selector("measurementWasSelected:smallUnit:element:"), origin: sender.superview!!.superview)

StringPicker.showActionSheetPicker()

**Comment by onlyfew** [comment] 2015-11-03 01:42
I fix this bug like this. Find string in AbstractActionSheetPicker.m
> [popover presentPopoverFromRect:_containerView.bounds inView:_containerView
                   permittedArrowDirections:UIPopoverArrowDirectionAny animated:YES];

replace with
> [popover presentPopoverFromRect:CGRectMake(_containerView.frame.size.width / 2.f, _containerView.frame.size.height / 2.f, 0, 0) inView:_containerView permittedArrowDirections:UIPopoverArrowDirectionAny animated:YES];

**Comment by Rommanski** [comment] 2015-11-15 00:34
Thank you @onlyfew it's works for me!

**Comment by skywinder** [comment] 2015-11-16 09:01
@onlyfew Thanks for solution. Is it works with all iOS veriosos w\o a problem? If so, I will be glad to accept PR with this fix from you!

**Comment by tulurira** [comment] 2015-11-16 09:01
NAVER - http://www.naver.com/
--------------------------------------------

tulurira3@naver.com 님께 보내신 메일 <Re: [ActionSheetPicker-3.0] ActionSheetStringPicker not working on iPad (only iPhone) (#156)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by skywinder** [comment] 2015-12-04 07:48
Is #131 fix this issue?

**Comment by skywinder** [comment] 2015-12-04 08:03
@onlyfew with this fix, that you provided Picker stops presenting from `UIbarbuttonitem`

**Comment by sparke16** [comment] 2016-04-06 19:36
I'm using the latest version (2.0.5 as of this writing) but I found I still had to manually put this code in, in order to get the iPad to show the action picker. Forgive my ignorance but when will this fix be available in the podspec?

**Comment by mikemike396** [comment] 2016-07-14 20:10
@sparke16 Same here! I am still getting this issue on 2.2. Any plans to make this available?

**Comment by skywinder** [comment] 2016-07-15 08:38
@sparke16 oh, probably something went wrong. it should be fixed already. Since you already put code in right place to fix this, can you make a PR with this  fix?

**Comment by dereksweet** [comment] 2016-08-03 03:50
I have this issue as well currently, and manually replacing the code that @onlyfew suggested does not seem to be fixing it either. I may just not know how to properly update pod code, however.. Have never done it before..

**Comment by canaksoy** [comment] 2017-04-14 08:27
not working. [Warning] <_UIPopoverBackgroundVisualEffectView 0x7fb30d46e490> is being asked to animate its opacity. This will cause the effect to appear broken until opacity returns to 1.

**Comment by alperkayabasi** [comment] 2017-04-25 10:35
same issue happened with the latest version, @giantslogik 's fix worked for me.

**Comment by lvandyk** [comment] 2018-01-25 13:01
Any update on this or should I create a fork?

**Comment by mbijapur** [comment] 2019-05-09 12:32
@onlyfew It worked for me. Thanks. But which pod version has this change? I am not able to get this change in latest pod version.

**Comment by Hardiktspaceo** [comment] 2019-05-17 06:15
@skywinder i am facing issue in **iPad** when i use **ActionSheetDatePicker** and **ActionSheetStringPicker**.

Here is my code 

`ActionSheetDatePicker.show(withTitle: "Select Date", datePickerMode: .date, selectedDate: Date(), minimumDate: minDate, maximumDate: Date(), doneBlock: { (picker, date, origin) in
                            self.selectedDate = date as! Date
                            self.fetchWeightLogRecords(with: self.selectedDate)
                            
                        }, cancel: nil, origin: self.view)
`

`ActionSheetStringPicker.show(withTitle: "Select Year", rows: arrYears, initialSelection: arrYears.count - 1, doneBlock: { (picker, index, value) in
                                    print("YEAR :: \(value!)")
                                    self.selectedYear = value as! Int
                                    self.arrLogWeight.removeAll()
                                    
                                    self.delay(0.1, closure: {
                                        self.fetchWholeYearAvgWeightData()
                                    })
                                    
                                }, cancel: nil, origin: self.view)`

Can you please help me in this...

**Comment by forestallers** [comment] 2019-06-04 12:40
> I fix this bug like this. Find string in AbstractActionSheetPicker.m
> 
> > [popover presentPopoverFromRect:_containerView.bounds inView:_containerView
> > permittedArrowDirections:UIPopoverArrowDirectionAny animated:YES];
> 
> replace with
> 
> > [popover presentPopoverFromRect:CGRectMake(_containerView.frame.size.width / 2.f, _containerView.frame.size.height / 2.f, 0, 0) inView:_containerView permittedArrowDirections:UIPopoverArrowDirectionAny animated:YES];

Its working form me. but @skywinder it will better if we can have this in next release.

**Comment by VivekVithlani** [comment] 2019-06-09 18:56
Don’t pass 

> @skywinder i am facing issue in **iPad** when i use **ActionSheetDatePicker** and **ActionSheetStringPicker**. pod version : ActionSheetPicker-3.0 (2.3.0)
> 
> Here is my code
> 
> ```
> ActionSheetDatePicker.show(withTitle: "Select Date", datePickerMode: .date, selectedDate: Date(), minimumDate: minDate, maximumDate: Date(), doneBlock: { (picker, date, origin) in
>                             self.selectedDate = date as! Date
>                             self.fetchWeightLogRecords(with: self.selectedDate)
>                             
>                         }, cancel: nil, origin: self.view)
> ```
> 
> ```
> ActionSheetStringPicker.show(withTitle: "Select Year", rows: arrYears, initialSelection: arrYears.count - 1, doneBlock: { (picker, index, value) in
>                                     print("YEAR :: \(value!)")
>                                     self.selectedYear = value as! Int
>                                     self.arrLogWeight.removeAll()
>                                     
>                                     self.delay(0.1, closure: {
>                                         self.fetchWholeYearAvgWeightData()
>                                     })
>                                     
>                                 }, cancel: nil, origin: self.view)
> ```
> 
> Can you please help me in this...

Hey

Don’t pass self.view in origin please
pass button or text field.

If user click on button then show picker so please pass button in origin,
If user click on textfield then show picket then pass textfield in origin.

**Comment by skywinder** [comment] 2019-12-10 17:59
Hello. please check the latest version. Should be fixed. 
Feel free to reopen the issue, if you still need help. 👍

**Closed by skywinder** 2019-12-10 17:59 UTC
Labels: bug
