### ISSUE TITLE
Tap to dismiss

### ISSUE THREAD

**Issue by havocked** [skywinder/ActionSheetPicker-3.0#138] opened 2015-02-13 12:11 UTC
Tap to dismiss outside pickerView would be a great feature !

Great work !

**Comment by skywinder** [comment] 2015-02-13 14:41
Hi. It's duplicate of #80. (so, you can upvote it by leave a comment there)
And @jklp try to implement it in #82, but it still not works on iOS 7, so I can't merge it yet.

**Closed by skywinder** 2015-02-13 14:41 UTC
