### ISSUE TITLE
TapAction calls the wrong method (on iOS 7 only)

### ISSUE THREAD

**Issue by StefanStefan** [skywinder/ActionSheetPicker-3.0#173] opened 2015-04-24 09:24 UTC
Hi,
I detected an issue with the TapAction feature.
It works fine on iOS 8, but causes a strange issue on iOS 7.
Question: If you want to activate the TapAction, you should set tapDismissAction equal to TapActionCancel or TapActionSuccess, right? So, if you do this and then are trying to use CANCEL Button, it calls "actionPickerDone" method instead of "actionPickerCancel". Similar problem, if you set tapDismissAction = TapActionSuccess (pressing DONE button calls the "actionPickerCancel") method. Again, this happens only on iOS 7. Can you fix this please? Thanks!

**Comment by skywinder** [comment] 2015-04-24 09:56
@StefanStefan hi! Can you provide some code example to reproduce this issue?

**Comment by StefanStefan** [comment] 2015-04-24 11:34
I uploaded a demo project. Could you check it!

https://github.com/StefanStefan/ActionPickerBUGDemo

**Comment by StefanStefan** [comment] 2015-04-24 11:59
Opps, sorry, I noticed there is problem in my uploaded project. How can I send you my project? email maybe?

**Comment by skywinder** [comment] 2015-04-24 16:04
Ok, thanks. I will look at it. But can't promise you solution next 2 weeks -
have a lot of tasks right now.

**Comment by StefanStefan** [comment] 2015-04-24 16:41
Ok! Thank you!

**Comment by foxluqi** [comment] 2015-05-07 06:07
I also encounter this issue in iOS7.
It seems below commands add a tapGestureRecongnizer which eats the touch of done or cancel button.
[self.actionSheet.window addGestureRecognizer:tapAction];

**Comment by skywinder** [comment] 2015-05-07 08:07
@BruceZCQ Please, look at it, probably you have idea, what goes wrong here.
(since we are implement this feature with you. :octocat: :octocat:  )

**Comment by BruceZCQ** [comment] 2015-05-07 09:11
@skywinder , may be need remove the UITapGestureRecognizer.  I will follow up and fix this bug.

**Comment by foxluqi** [comment] 2015-05-07 10:17
@BruceZCQ @skywinder pls check if my fix works.
Thanks.

**Comment by skywinder** [comment] 2015-05-07 10:38
@foxluqi You did it! awesome! :gem: 
Fixed in #176

**Closed by skywinder** 2015-05-07 10:38 UTC
Labels: bug
